#!/bin/sh

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting VPN"
    /usr/share/vpn-over-ssh/vos-start &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon vosd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping VPN"
    /usr/share/vpn-over-ssh/vos-stop &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon vosd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
